export default {
    share_content: '推荐新用户好友购买立享10%返现',
    home: "首页",
    ticket: "车票",
    promotion: "推广",
    order: "订单",
    mine: "我的",
    terms_use: "使用条款",
    help_center: "帮助中心",
    concact_us: "联系我们",
    home_title: "探索视界  重新出发",
    home_sub_title: "IShare是一个安全的，便捷的，省心的账号合租平台，为您提供可靠、独立、安全的账号合租服务，是我们的服务核心。",
    all: "全部",
    video: "影视",
    music: "音乐",
    storage: '储存',
    learn: "学习",
    develop: "开发",
    only_title: "享受专属优势",
    laws_service: "法律服务",
    laws_service_content: "是的，共享订阅是合法的。内容或服务提供商本身允许您共享。 IShare为您提供简单、更安全的支付和退款管理服务。",
    product_plan: "买家保护计划",
    product_plan_cotnent: "您的所有购买都受到保护：我们保证订阅的正常运行，或者免费为您退款。付款后，您就可以访问共享订阅。如果您有问题，我们的团队将检查并在必要时免费退款给您。",
    for_free: "您分享时不收取任何费用。",
    for_free_content: "收款不收取任何费用：向您的银行账户转账是免费的，并且在您达到最低金额后会自动处理。",
    product_data: "保护数据",
    product_data_content: "如果您需要共享 ID、密码、许可证号或其他信息等机密数据，IShare 是保护这些数据的正确解决方案。您的交易将通过强加密 (AES 256) 进行传输和存储，以确保您的隐私。",
    normal_ques: "经常问的问题",
    my_ticket: "我的车票",
    in_car: "已上车",
    out_car: "已下车",
    join_group: "加入售后群",
    oreder_number: "订单号",
    start_time: "开始时间",
    end_Time: "到期时间",
    account: "账号",
    password: "密码",
    use_guid: "使用说明",
    check_now: "立即查看",
    seat_number: "座位号",
    account_renew: "原号续费"
}